### ISSUE TITLE
Links in tables "float" when the plugin is enabled.

### ISSUE THREAD

**Issue by solargate** [MrGVSV/obsidian-github-embeds#3]
Hi!

I'm seeing strange behavior in Markdown-tables when the GitHub Embeds plugin is enabled.

Behavior without plugin enabled:

![Screenshot from 2023-10-10 23-48-41](https://github.com/MrGVSV/obsidian-github-embeds/assets/11595907/37613ae4-9a84-40cf-a298-78faf0c8dd02)

Behavior with plugin enabled:

![image](https://github.com/MrGVSV/obsidian-github-embeds/assets/11595907/3abf7c73-ee45-419d-a31e-41be799f99f5)

It would be great to fix this...

Thanks for plugin!

**Comment by MrGVSV** [comment]
I'll look into this!
