### ISSUE TITLE
File linking no longer works

### ISSUE THREAD

**Issue by tgruben** [MrGVSV/obsidian-github-embeds#31]
# Description
Displaying file snippets no longer works,  it has worked fine until the last week or so

# Details

## Reproduction Steps

<details><summary>Markdown</summary>
Any github link that used to work great now results in an error
```md
https://github.com/FeatureBaseDB/featurebase/blob/6222e9eb58c6906f3fa7e084a651d53bd62f303a/bsi.go#L18
```

</details>

## Expected Behavior

Display the code slug

## Actual Behavior

The message bellow is displayed

Error loading GitHub embedTypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined

## Screenshots

![image](https://github.com/MrGVSV/obsidian-github-embeds/assets/889059/b4718876-662d-4bda-999a-b419d22b4eda)

# Additional Context

- **Obsidian version:** 
1.5.12
- **Plugin version:** 
1.0.7

**Comment by tgruben** [comment]
Well turns out my token had expired, not a real clear error message but all is right in the world again

**Comment by MrGVSV** [comment]
Maybe we could add a better error message for expired tokens 🤔
